---
title: "FAMe_analysis"
author: "Annabel Critchlow"
date: "2024-11-14"
output:
  html_document:
    theme: readable
    toc: TRUE
---


# Set working directory

```{r}
setwd("C:/Users/annab/OneDrive - Deakin University/PhD/Studies/FAMe Study/FAMe Data Analysis/R analysis")

library(tidyverse)
library(dplyr)
library(readxl)
library(gtsummary)
library(cardx)
library(gt)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(mgcv)
library(dplyr)
library(knitr)
library(kableExtra)
library(broom)
library(ggbreak)
library(patchwork)
```


# Load file

```{r}
data <- read_excel("C:/Users/annab/OneDrive - Deakin University/PhD/Studies/FAMe Study/FAMe Data Analysis/FAMe_Data_[AC].xlsx",
                   na = c("","NA", "?", "#VALUE!"),
                 trim_ws = TRUE)

immuno_data <- data %>%
  filter(ihc == "yes")

rna_data <- data %>%
  filter(!is.na(rnaseq) & rnaseq != "", id != "92")
    
```

# Participant characteristics

## Define variables

```{r}
numvars <- c("weight", "height", "bmi", "bodyfat", "TBFM", "TBLM", "ALM", "ALMh", "bmc", "thighmuscle", "intrafat", "subfat", "permuscle", "bonedensity", "Ipernumber", "Iperarea", "Imeanarea", "IIapernumber", "IIaperarea", "IIameanarea", "Hybridpernumber", "Hybridperarea", "Hybridmeanarea", "Tmeanarea", "onerep", "onerepllm", "onerepcsa", "E2", "FEI", "prog", "TT", "FAI", "TEratio", "protein", "mvpa")

catvars <- c("meno", "hc", "hrt")

data$agecat <- as.factor(data$agecat)
```


## Calculate mean/SD

Replace data input for each subset.

```{r}

# Step 1: Numeric summary by agecat
by_agecat_num <- rna_data %>%
  group_by(agecat) %>%
  summarise(across(all_of(numvars),
                   list(mean = ~round(mean(.x, na.rm = TRUE), 1),
                        sd   = ~round(sd(.x, na.rm = TRUE), 1)),
                   .names = "{.col}_{.fn}")) %>%
  pivot_longer(-agecat, names_to = c("Variable", "Stat"), names_sep = "_") %>%
  pivot_wider(names_from = Stat, values_from = value) %>%
  mutate(Value = paste0(mean, " (", sd, ")")) %>%
  select(agecat, Variable, Value)

# Step 2: Overall numeric summary
overall_num <- rna_data %>%
  summarise(across(all_of(numvars),
                   list(mean = ~round(mean(.x, na.rm = TRUE), 1),
                        sd   = ~round(sd(.x, na.rm = TRUE), 1)),
                   .names = "{.col}_{.fn}")) %>%
  pivot_longer(everything(), names_to = c("Variable", "Stat"), names_sep = "_") %>%
  pivot_wider(names_from = Stat, values_from = value) %>%
  mutate(Value = paste0(mean, " (", sd, ")"),
         agecat = "Overall") %>%
  select(agecat, Variable, Value)

# Step 3: Combine numeric summary
summary_num <- bind_rows(by_agecat_num, overall_num) %>%
  pivot_wider(names_from = agecat, values_from = Value) %>%
  mutate(Stat = "mean (sd)") %>%
  select(Variable, Stat, everything())

# Step 4: Count total per group (agecat) for percentage calculation
agecat_totals <- rna_data %>%
  group_by(agecat) %>%
  summarise(N = n(), .groups = "drop")

# Step 5: Categorical summary by agecat as "n / total (percent%)"
by_agecat_cat <- rna_data %>%
  select(agecat, all_of(catvars)) %>%
  pivot_longer(-agecat, names_to = "Variable", values_to = "Level") %>%
  group_by(agecat, Variable, Level) %>%
  summarise(n = n(), .groups = "drop") %>%
  left_join(agecat_totals, by = "agecat") %>%
  mutate(pct = round(100 * n / N, 1),
         Value = paste0(n, " / ", N, " (", pct, "%)")) %>%
  unite(Variable, Variable, Level, sep = ": ") %>%
  select(agecat, Variable, Value) %>%
  pivot_wider(names_from = agecat, values_from = Value)

# Step 6: Overall counts for categorical variables
overall_cat <- rna_data %>%
  select(all_of(catvars)) %>%
  pivot_longer(everything(), names_to = "Variable", values_to = "Level") %>%
  group_by(Variable, Level) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(N = nrow(data),
         pct = round(100 * n / N, 0),
         Overall = paste0(n, " / ", N, " (", pct, "%)")) %>%
  unite(Variable, Variable, Level, sep = ": ") %>%
  select(Variable, Overall)

# Step 7: Combine categorical summaries
summary_cat <- full_join(by_agecat_cat, overall_cat, by = "Variable") %>%
  mutate(Stat = "count / total (%)") %>%
  select(Variable, Stat, everything())

# Step 8: Final combined summary table
final_table <- bind_rows(summary_num, summary_cat)

# Step 9: Export
print(final_table, n = Inf)
write_csv(final_table, "rna_participant_characteristics.csv")

```


# Hormonal effects

## Menstrual cycle phase

```{r}
# Create subset of data with only premenopausal participants
mcdata <- data %>%
  filter(meno == "Premenopausal", neurophase != "unknown", hc != "OCP", hc != "Implant") %>%
  drop_na(neurophase)

# Select which variables to analyse and place them in a list
vars <- mcdata %>%
  dplyr::select("onerep", "onerepllm", "onerepcsa")

vars <- names(vars)

models = lapply(vars, function(x) {
  lm(substitute(i ~ neurophase, list(i = as.name(x))), data = mcdata)
})

y=lapply(models, summary)
names(y) <- vars # To add names of the model instead of list number
df=purrr::map_df(y, broom::tidy, .id = 'vars')%>%
  filter(term == "neurophase" | term != "(Intercept)")

knitr::kable(df) %>%
  kable_styling() %>%
  row_spec(which(df$term == "neurophase"  & df$p.value < 0.05), bold = T)

write.csv(df, "Hormone_effects/Menstrual_cycle_effects.csv")

# Plots
plot_list<- vector('list', 3)
names(plot_list) <- vars
for(i in vars){
  plot_list[[i]] <- 
    ggplot(mcdata, aes(x=neurophase, y=.data[[i]], color=neurophase)) +
    geom_point(size=3)+
    geom_boxplot()+
    theme(text = element_text(face="bold", size=16), panel.background = element_blank(), axis.line=  element_line(colour = "black"))
}
#Combine plots
combined_plot <- wrap_plots(plot_list, ncol = 3)  # Adjust ncol for number of columns
ggsave("Hormone_effects/Menstrual_cycle_effects_plots.pdf", combined_plot, width = 20, height = 10)



```

## Contraceptives

```{r}
# Create subset of data with only premenopausal participants
predata <- data %>%
  filter(meno == "Premenopausal") %>%
  drop_na(hc) %>%
  mutate(hc = factor(hc, levels = c("None", "OCP", "IUD", "Implant")))

# Select which variables to analyse and place them in a list
vars <- predata %>%
  dplyr::select("bodyfat", "TBFM", "TBLM", "ALM", "ALMh", "thighmuscle", "intrafat", "subfat", "permuscle", "onerep", "onerepllm", "onerepcsa")

vars <- names(vars)

models = lapply(vars, function(x) {
  lm(substitute(i ~ hc, list(i = as.name(x))), data = predata)
})

y=lapply(models, summary)
names(y) <- vars # To add names of the model instead of list number
df=purrr::map_df(y, broom::tidy, .id = 'vars')%>%
  filter(term == "hc" | term != "(Intercept)")

knitr::kable(df) %>%
  kable_styling() %>%
  row_spec(which(df$term == "hc"  & df$p.value < 0.05), bold = T)

write.csv(df, "Hormone_effects/Contraceptive_effects.csv")

# Plots
plot_list<- vector('list', 12)
names(plot_list) <- vars
for(i in vars){
  plot_list[[i]] <- 
    ggplot(predata, aes(x=hc, y=.data[[i]], color=hc)) +
    geom_point(size=3)+
    geom_boxplot()+
    theme(text = element_text(face="bold", size=16), panel.background = element_blank(), axis.line=  element_line(colour = "black"))
}
#Combine plots
combined_plot <- wrap_plots(plot_list, ncol = 3)  # Adjust ncol for number of columns
ggsave("Hormone_effects/Contraceptive_effects_plots.pdf", combined_plot, width = 20, height = 30)

```

## HRT

```{r}
# Create subset of data with only peri and postmenopausal participants
peripostdata <- data %>%
  filter(meno != "Premenopausal") %>%
  drop_na(hrt) %>%
  mutate(hrt = factor(hrt, levels = c("Not currently using", "Currently using")))

# Select which variables to analyse and place them in a list
vars <- peripostdata %>%
  dplyr::select("bodyfat", "TBFM", "TBLM", "ALM", "ALMh", "thighmuscle", "intrafat", "subfat", "permuscle", "onerep", "onerepllm", "onerepcsa")

vars <- names(vars)

models = lapply(vars, function(x) {
  lm(substitute(i ~ hrt, list(i = as.name(x))), data = peripostdata)
})

y=lapply(models, summary)
names(y) <- vars # To add names of the model instead of list number
df=purrr::map_df(y, broom::tidy, .id = 'vars')%>%
  filter(term == "hrt" | term != "(Intercept)")

knitr::kable(df) %>%
  kable_styling() %>%
  row_spec(which(df$term == "hrt"  & df$p.value < 0.05), bold = T)

write.csv(df, "Hormone_effects/HRT_effects.csv")

# Plots
plot_list<- vector('list', 12)
names(plot_list) <- vars
for(i in vars){
  plot_list[[i]] <- 
    ggplot(peripostdata, aes(x=hrt, y=.data[[i]], color=hrt)) +
    geom_point(size=3)+
    geom_boxplot()+
    theme(text = element_text(face="bold", size=16), panel.background = element_blank(), axis.line=  element_line(colour = "black"))
}
#Combine plots
combined_plot <- wrap_plots(plot_list, ncol = 3)  # Adjust ncol for number of columns
ggsave("Hormone_effects/HRT_plots.pdf", combined_plot, width = 20, height = 30)
```



